spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: irisa
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: irisarolande25@gmail.com
    password: bjoy vqlt ggib gkaj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

jwt:
  secret: VGhpc2lzYVN1cGVyTG9uZ0FuZFNlY3VyZUpXVFNlY3JldEtleUZvckhTNTEyVGhhdElzTWFkZVVwT2ZTcGVjaWFsQ2hhcmFjdGVycyE=
  expiration: 86400000 # 24 hours in milliseconds

app:
  cors:
    allowed-origins: http://localhost:3000
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    max-age: 3600 